scan_timeout = 10

[character]
error_symbol = "[â¯â¯â¯](bold red)"
success_symbol = "[â¯â¯â¯](bold cyan)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "â€¦/"

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"

[aws.region_aliases]
ap-northeast-1 = "jp"

[custom.arch]
command = "uname -m"
when = """ test $(uname -m) = "x86_64" """
style = "bold yellow"
format = "[$output]($style)"

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[git_branch]
symbol = "ïˆ "

[python]
symbol= "ï Ÿ "

[php]
symbol="ï  "

[ruby]
symbol="îœ¹ (bold red)"

#[docker]
#symbol="ïŒˆ"


[username]
#style_user = "bold green"
# style_root = "black bold"
# format = "STOICNEET($style_user) "
style_user = "bold cyan"
# style = "bold dimmed green"
# style_user = "blue bold"
# style_root = "black bold"
# format = "[STOICNEETïŠ‡ ]($style) "
#format = "[STOICNEETîˆ´îˆ´îˆ´]($style) "
#format = "[STOICNEETï¯¢ ]($style) "
disabled = false
show_always = true

